name: build
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Flutter
        uses: britannio/action-install-flutter@v1
      - name: install dependencies
        uses: steebchen/flutter@v1.1.0
        with:
          args: pub get
      - name: Build Installer
        uses: steebchen/flutter@v1.1.0
        with:
          args: pub run msix:build
      - uses: actions/upload-artifact@v3
        with:
          name: WindowsInstaller
          path: build/windows/runner/Release/mod_version_checker.msix
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Flutter
        uses: britannio/action-install-flutter@v1
      - name: Setup Ninja
        uses: ashutoshvarma/setup-ninja@master
      - name: Get Packages
        run: flutter pub get
      - name: Build Linux
        run: flutter build linux --release
      - uses: actions/upload-artifact@v3
        with:
          name: ModVersionCheckerLinux
          path: build/linux/release/bungle/mod_version_checker
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Flutter
        uses: britannio/action-install-flutter@v1
      - name: Get Packages
        run: flutter pub get
      - name: Build Linux
        run: flutter build macos --release -v

